import { prisma } from "../db";
import { postToThread } from "./helpers";
import { execFile } from "child_process";
import { promisify } from "util";

const execFileAsync = promisify(execFile);

export async function runFallback(
  jobId: number,
  context: string,
  repoSlug: string,
  threadId: string,
) {
  const repo = await prisma.repository.findUnique({ where: { slug: repoSlug } });
  if (!repo) return;

  await postToThread(threadId, "ℹ️ No worker online — running fallback path...");

  try {
    // Check if issue was already generated by the bot
    const job = await prisma.job.findUnique({ where: { id: jobId } });

    let issueNumber = job?.issueNumber;
    let issueUrl: string;

    if (!issueNumber) {
      // Model stored in DB; no env variable
      const setting = await prisma.setting.findUnique({ where: { key: "fallback_model" } });
      const model = setting?.value ?? "opencode/big-pickle";

      const prompt = [
        `Analyse the following Discord thread context and produce a structured GitHub issue.`,
        `Repository: ${repoSlug} (at ${repo.path})`,
        ``,
        `Output ONLY:`,
        `Line 1: The issue title (plain text, no markdown heading)`,
        `Line 2+: The issue body in Markdown`,
        ``,
        `Context:`,
        context,
      ].join("\n");

      const proc = Bun.spawn(["opencode", "run", "--model", model, "--print", prompt], {
        cwd: repo.path,
        stdout: "pipe",
        stderr: "pipe",
      });

      const stdout = await new Response(proc.stdout).text();
      const exitCode = await proc.exited;

      if (exitCode !== 0) {
        const stderr = await new Response(proc.stderr).text();
        await postToThread(threadId, `❌ Fallback opencode failed (exit ${exitCode}): ${stderr.slice(0, 500)}`);
        await prisma.job.update({ where: { id: jobId }, data: { status: "failed" } });
        return;
      }

      const lines = stdout.trim().split("\n");
      const title = lines[0]?.replace(/^#+\s*/, "").trim() || `[${repoSlug}] Automated issue`;
      const body = lines.slice(1).join("\n").trim() || `Automated issue for ${repoSlug}`;

      await postToThread(threadId, "ℹ️ Creating GitHub issue...");

      let repoNameWithOwner: string;
      try {
        const { stdout: ghRepoOut } = await execFileAsync(
          "gh",
          ["repo", "view", "--json", "nameWithOwner", "--jq", ".nameWithOwner"],
          { cwd: repo.path },
        );
        repoNameWithOwner = ghRepoOut.trim();
      } catch {
        repoNameWithOwner = "";
      }

      const ghArgs = [
        "issue", "create",
        "--title", title,
        "--body", body,
        ...(repoNameWithOwner ? ["--repo", repoNameWithOwner] : []),
      ];

      const ghProc = Bun.spawn(["gh", ...ghArgs], {
        cwd: repo.path,
        stdout: "pipe",
        stderr: "pipe",
      });

      const ghOutput = await new Response(ghProc.stdout).text();
      const ghExit = await ghProc.exited;

      if (ghExit !== 0) {
        const ghErr = await new Response(ghProc.stderr).text();
        await postToThread(threadId, `❌ Failed to create GitHub issue: ${ghErr.slice(0, 500)}`);
        await prisma.job.update({ where: { id: jobId }, data: { status: "failed" } });
        return;
      }

      issueUrl = ghOutput.trim();

      const match = issueUrl.match(/\/(\d+)$/);
      if (match && match[1]) {
        issueNumber = parseInt(match[1]);
        await prisma.job.update({ where: { id: jobId }, data: { issueNumber } });
      }

      await postToThread(threadId, `✅ Issue created: ${issueUrl}`);
    } else {
      // Use pre-generated issue
      const repoNameWithOwner = await getRepoNameWithOwner(repo.path);
      issueUrl = repoNameWithOwner
        ? `https://github.com/${repoNameWithOwner}/issues/${issueNumber}`
        : `issue #${issueNumber}`;
    }

    const commentProc = Bun.spawn(
      ["gh", "issue", "comment", issueUrl, "--body", "/opencode fix this issue in a PR"],
      { cwd: repo.path, stdout: "pipe", stderr: "pipe" },
    );
    await commentProc.exited;

    await postToThread(threadId, `✅ Triggered opencode on the issue. Job complete.\n${issueUrl}`);
    await prisma.job.update({ where: { id: jobId }, data: { status: "done" } });
  } catch (err) {
    await postToThread(threadId, `❌ Fallback path error: ${err}`);
    await prisma.job.update({ where: { id: jobId }, data: { status: "failed" } });
  }
}

async function getRepoNameWithOwner(repoPath: string): Promise<string> {
  try {
    const { stdout } = await execFileAsync(
      "gh",
      ["repo", "view", "--json", "nameWithOwner", "--jq", ".nameWithOwner"],
      { cwd: repoPath },
    );
    return stdout.trim();
  } catch {
    return "";
  }
}

export async function checkWorkerOnline(): Promise<boolean> {
  const settings = await prisma.setting.findMany({
    where: { key: { startsWith: "worker:" } },
  });

  const now = Date.now();
  for (const s of settings) {
    if (s.key.endsWith(":lastSeen")) {
      const lastSeen = new Date(s.value).getTime();
      if (now - lastSeen < 60_000) return true;
    }
  }

  return false;
}
